import json
from typing import Optional


class ScriptedLLMClient:
    """Offline LLMClient for ``--dry-run``: returns canned, schema-valid JSON
    so the pipeline runs end-to-end with no API key. It routes by inspecting
    the system prompt, which differs per judgment call site.
    """

    def __init__(
        self,
        dead_code_verdict: str = "dead",
        owner: Optional[str] = None,
        risk_justification: str = "Dry-run: risk justification not generated by a real model.",
    ):
        self.dead_code_verdict = dead_code_verdict
        self.owner = owner
        self.risk_justification = risk_justification
        self.calls: list = []

    def complete(self, system_prompt: str, user_prompt: str) -> str:
        self.calls.append((system_prompt, user_prompt))
        # Route on the quoted JSON-key token from each prompt's response
        # schema. Bare "owner" would false-match the risk-justification
        # prompt, whose prose contains the word "owners".
        if '"verdict"' in system_prompt:
            return json.dumps(
                {
                    "verdict": self.dead_code_verdict,
                    "justification": "dry-run: no model was called",
                }
            )
        if '"owner"' in system_prompt:
            chosen = self.owner or self._first_tied_owner(user_prompt)
            return json.dumps(
                {"owner": chosen, "justification": "dry-run: first tied owner"}
            )
        return json.dumps({"justification": self.risk_justification})

    @staticmethod
    def _first_tied_owner(user_prompt: str) -> str:
        marker = "Tied candidate owners:"
        if marker in user_prompt:
            tail = user_prompt.split(marker, 1)[1].strip()
            first = tail.splitlines()[0].split(",")[0].strip()
            if first:
                return first
        return "unknown"
